#services:
#  postgres:
#    image: postgres:latest
#    container_name: product_inventory_db
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5433:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
#      interval: 5s
#      timeout: 5s
#      retries: 30
#      start_period: 5s
#
#  backend:
#    build: .
#    container_name: product_inventory_backend
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/postgres
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#volumes:
#  postgres_data: